"""initial schema

Revision ID: d112464ccd63
Revises: 
Create Date: 2026-09-16 00:51:04.993642
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd112464ccd63'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.Enum('SEV1', 'SEV2', 'SEV3', 'SEV4', name='severity', native_enum=False, length=16), nullable=False),
    sa.Column('status', sa.Enum('DETECTED', 'INVESTIGATING', 'AWAITING_APPROVAL', 'MITIGATING', 'MITIGATED', 'RESOLVED', name='incidentstatus', native_enum=False, length=32), nullable=False),
    sa.Column('affected_service', sa.String(length=255), nullable=False),
    sa.Column('assigned_operator', sa.String(length=255), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('runbooks',
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=False),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('audit_events',
    sa.Column('incident_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.Enum('INCIDENT_CREATED', 'EVIDENCE_ADDED', 'ASSESSMENT_REQUESTED', 'ASSESSMENT_GENERATED', 'ASSESSMENT_VALIDATION_FAILED', 'REMEDIATION_PROPOSED', 'APPROVAL_REQUESTED', 'REMEDIATION_APPROVED', 'REMEDIATION_REJECTED', 'SIMULATED_REMEDIATION_STARTED', 'SIMULATED_REMEDIATION_COMPLETED', 'SIMULATED_REMEDIATION_FAILED', 'POST_INCIDENT_REPORT_GENERATED', 'SALESFORCE_SYNC_REQUESTED', 'SALESFORCE_SYNC_COMPLETED', 'SALESFORCE_SYNC_FAILED', name='auditeventtype', native_enum=False, length=48), nullable=False),
    sa.Column('actor_type', sa.Enum('OPERATOR', 'SYSTEM', 'AI', name='actortype', native_enum=False, length=16), nullable=False),
    sa.Column('actor_id', sa.String(length=255), nullable=False),
    sa.Column('previous_state', sa.String(length=32), nullable=True),
    sa.Column('new_state', sa.String(length=32), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_incident_id'), 'audit_events', ['incident_id'], unique=False)
    op.create_table('evidence_records',
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('evidence_type', sa.Enum('ALERT', 'METRIC', 'LOG', 'DEPLOYMENT', 'RUNBOOK', 'OPERATOR_NOTE', name='evidencetype', native_enum=False, length=32), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_records_incident_id'), 'evidence_records', ['incident_id'], unique=False)
    op.create_table('incident_assessments',
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('SEV1', 'SEV2', 'SEV3', 'SEV4', name='severity', native_enum=False, length=16), nullable=False),
    sa.Column('affected_services', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('likely_root_cause', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('evidence_references', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('runbook_references', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommended_next_steps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('uncertainties', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('safety_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('validation_status', sa.Enum('VALID', 'INVALID_FALLBACK', name='validationstatus', native_enum=False, length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_assessments_incident_id'), 'incident_assessments', ['incident_id'], unique=False)
    op.create_table('integration_syncs',
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('integration', sa.String(length=64), nullable=False),
    sa.Column('sync_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'COMPLETED', 'FAILED', name='integrationsyncstatus', native_enum=False, length=16), nullable=False),
    sa.Column('external_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_syncs_incident_id'), 'integration_syncs', ['incident_id'], unique=False)
    op.create_table('post_incident_reports',
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('timeline_summary', sa.Text(), nullable=False),
    sa.Column('customer_impact_summary', sa.Text(), nullable=False),
    sa.Column('root_cause_summary', sa.Text(), nullable=False),
    sa.Column('remediation_summary', sa.Text(), nullable=False),
    sa.Column('follow_up_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('lessons_learned', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_incident_reports_incident_id'), 'post_incident_reports', ['incident_id'], unique=False)
    op.create_table('remediation_proposals',
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('assessment_id', sa.String(length=36), nullable=True),
    sa.Column('action_type', sa.Enum('ROLLBACK_DEPLOYMENT', 'DISABLE_FEATURE_FLAG', 'SCALE_SERVICE', name='actiontype', native_enum=False, length=32), nullable=False),
    sa.Column('action_description', sa.Text(), nullable=False),
    sa.Column('justification', sa.Text(), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risklevel', native_enum=False, length=16), nullable=False),
    sa.Column('blast_radius', sa.Text(), nullable=False),
    sa.Column('prerequisites', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rollback_plan', sa.Text(), nullable=False),
    sa.Column('expected_outcome', sa.Text(), nullable=False),
    sa.Column('required_approval', sa.Boolean(), nullable=False),
    sa.Column('evidence_references', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('runbook_references', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'EXECUTING', 'EXECUTED', 'FAILED', name='proposalstatus', native_enum=False, length=32), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['incident_assessments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remediation_proposals_incident_id'), 'remediation_proposals', ['incident_id'], unique=False)
    op.create_table('remediation_approvals',
    sa.Column('proposal_id', sa.String(length=36), nullable=False),
    sa.Column('decision', sa.Enum('APPROVED', 'REJECTED', name='approvaldecision', native_enum=False, length=16), nullable=False),
    sa.Column('actor_type', sa.Enum('OPERATOR', 'SYSTEM', 'AI', name='actortype', native_enum=False, length=16), nullable=False),
    sa.Column('actor_id', sa.String(length=255), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['remediation_proposals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remediation_approvals_proposal_id'), 'remediation_approvals', ['proposal_id'], unique=False)
    op.create_table('remediation_executions',
    sa.Column('proposal_id', sa.String(length=36), nullable=False),
    sa.Column('action_type', sa.Enum('ROLLBACK_DEPLOYMENT', 'DISABLE_FEATURE_FLAG', 'SCALE_SERVICE', name='actiontype', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('STARTED', 'SUCCEEDED', 'FAILED', name='executionstatus', native_enum=False, length=16), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['remediation_proposals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remediation_executions_proposal_id'), 'remediation_executions', ['proposal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_remediation_executions_proposal_id'), table_name='remediation_executions')
    op.drop_table('remediation_executions')
    op.drop_index(op.f('ix_remediation_approvals_proposal_id'), table_name='remediation_approvals')
    op.drop_table('remediation_approvals')
    op.drop_index(op.f('ix_remediation_proposals_incident_id'), table_name='remediation_proposals')
    op.drop_table('remediation_proposals')
    op.drop_index(op.f('ix_post_incident_reports_incident_id'), table_name='post_incident_reports')
    op.drop_table('post_incident_reports')
    op.drop_index(op.f('ix_integration_syncs_incident_id'), table_name='integration_syncs')
    op.drop_table('integration_syncs')
    op.drop_index(op.f('ix_incident_assessments_incident_id'), table_name='incident_assessments')
    op.drop_table('incident_assessments')
    op.drop_index(op.f('ix_evidence_records_incident_id'), table_name='evidence_records')
    op.drop_table('evidence_records')
    op.drop_index(op.f('ix_audit_events_incident_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('runbooks')
    op.drop_table('incidents')
    # ### end Alembic commands ###
